version: '3.1'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: mtaa_backend
    env_file: ./.env
    environment:
        - USER=$DATABASE_USER
        - PASSWORD=$DATABASE_PASSWORD
        - NAME=$DATABASE_NAME
        - HOST=$DATABASE_HOST

  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: mtaa_app
      MYSQL_ROOT_PASSWORD: root
    container_name: mtaa_database

  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080
    depends_on:
      - "mydb"
    container_name: mtaa_sql_gui